#!/bin/bash
#===============================================================================
# Yane module for console management.
# Warning : this module doesn't work alone.
# You need yane_module_consoles_(xterm/tmux)
#===============================================================================

TMUX=/usr/bin/tmux

#-------------------------------------------------------------------------------
# Open a console in the shell
#   $1 : hostName
#-------------------------------------------------------------------------------
yaneOpenConsole () {
   c=$(eval yaneConsoleCmd_${hostMode[$1]} $1)
   logMessage LOG "Running console '$c'"
   $c
}

#-------------------------------------------------------------------------------
# Open console on listed hosts
#-------------------------------------------------------------------------------
yaneOpenConsoleWindows () {
   logMessage LOG "Opening consoles"
   for idx in ${!consHost[@]}
   do
     if [ "${consHost[$idx]}" = "xterm" ]; then
       yaneOpenConsoleWindow_xterm $idx
     elif [ "${consHost[$idx]}" = "tmux" ]; then
       yaneOpenConsoleWindow_tmux $idx
     fi
   done
   $TMUX has -t $SESSION_ID 2> /dev/null
   if [ $? -eq 0 ]; then
     $XTERM -e "tmux attach -t $SESSION_ID" &
     echo $! >> ./.yane_${SESSION_ID}_module_consoles.pid
   fi
}

#-------------------------------------------------------------------------------
# Kill all open consoles in $SESSION_ID
#-------------------------------------------------------------------------------
yaneKillConsoles () {
   logMessage LOG "Kill consoles"

   if [ -f ./.yane_${SESSION_ID}_module_consoles.pid ] ; then
      for c in `cat ./.yane_${SESSION_ID}_module_consoles.pid`
      do
          $KILL $c
      done
      $RM ./.yane_${SESSION_ID}_module_consoles.pid

      # Check if tmux. If true kill all tmux.
      $TMUX has -t $SESSION_ID 2> /dev/null
      if [ $? -eq 0 ]; then
        $TMUX kill-session -t $SESSION_ID
      fi
   fi
}
