#!/bin/bash
#===============================================================================
# Yane module for console management
#===============================================================================

TMUX=/usr/bin/tmux
#TNWIN=?
#-------------------------------------------------------------------------------
# Open a console in the shell
#   $1 : hostName
#-------------------------------------------------------------------------------
yaneOpenConsole () {
   c=$(eval yaneConsoleCmd_${hostMode[$1]} $1)
   logMessage LOG "Running console '$c'" 
   $c
}

#-------------------------------------------------------------------------------
# Open a console in a window in $SESSION_ID
#   $1 : hostName
#   $2 : tmux id window
#   $3 : tmux id pane
#-------------------------------------------------------------------------------
yaneOpenConsoleWindow () {
   c=$(eval yaneConsoleCmd_${hostMode[$1]} ${SESSION_ID}_$1)

   logMessage LOG "Running console '$c' in terminal '$t'" 

   tmux send-keys -t "session_$SESSION_ID:$2.$3" "$c" Enter

}

#-------------------------------------------------------------------------------
# Open console on listed hosts
#-------------------------------------------------------------------------------
yaneOpenConsoleWindows () {
   logMessage LOG "Opening consoles"
   
   
   NB_CONSOLES=${#consHost[@]}
   NB_WINDOWS=$(echo "$NB_CONSOLES/4 + 1" | bc)

   tmux new-session -s session_$SESSION_ID -d
   tkpanes $NB_CONSOLES session_$SESSION_ID
   
   idwindow=0
   idpane=0
   for hn in ${consHost[@]}
   do
      logMessage LOG "Opening console on $hn"
      yaneOpenConsoleWindow $hn $idwindow $idpane
      idpane=$(echo "($idpane+1)%4" | bc)
      if [ $idpane -eq 0 ]; then
         idwindow=$(echo "$idwindow+1" | bc)
      fi
   done
   xterm -e "tmux attach -t session_$SESSION_ID" &
   echo $! >> ./.yane_${SESSION_ID}_module_consoles.pid
}

#-------------------------------------------------------------------------------
# Kill all open consoles in $SESSION_ID
#-------------------------------------------------------------------------------
yaneKillConsoles () {
   logMessage LOG "Kill consoles"
   
   if [ -f ./.yane_${SESSION_ID}_module_consoles.pid ] ; then 
      for c in `cat ./.yane_${SESSION_ID}_module_consoles.pid`
      do
          $KILL $c
      done
      $RM ./.yane_${SESSION_ID}_module_consoles.pid
      tmux kill-session -t session_$SESSION_ID
   fi
}

