#!/bin/bash

#-------------------------------------------------------------------------------
# create service dnsmasq
#  $1 : hostname
#-------------------------------------------------------------------------------
createService_dnsmasq () {
   createHost_docker $1 "dnsmasq"
   hostName[$1]=$1
   hostMode[$1]="docker"
   hostImage[$1]="dnsmasq"
}

#-------------------------------------------------------------------------------
# shutdown service dnsmasq
#  $1 : hostname
#-------------------------------------------------------------------------------
shutdownService_dnsmasq () {
   shutdownHost_docker $1
}

#-------------------------------------------------------------------------------
# delete service dnsmasq
#  $1 : hostname
#-------------------------------------------------------------------------------
deleteService_dnsmasq () {
   deleteHost_docker $1
}
