#!/bin/bash
#===============================================================================
# Namespace helper functions
#===============================================================================
#-------------------------------------------------------------------------------
# create host
#    $1 : hostname
#-------------------------------------------------------------------------------
createHost_namespace () {
   logMessage LOG "Creating namespace $1"

   $IP netns del $1 > /dev/null 2>&1 ||$TRUE
   $IP netns add $1
   $IP netns exec $1 $IP link set lo up
}

#-------------------------------------------------------------------------------
# kill host
#    $1 : hostname
#-------------------------------------------------------------------------------
killHost_namespace () {
   logMessage LOG "Killing namespace $1"

   $IP netns del $1 > /dev/null 2>&1 ||$TRUE   
}

#-------------------------------------------------------------------------------
# return command that could open a terminal
#    $1 : hostname
#-------------------------------------------------------------------------------
yaneConsoleCmd_namespace() {
   echo "$IP netns exec $1 $BASH"
}


