#!/bin/bash
#===============================================================================
# netns helper functions
#===============================================================================
#-------------------------------------------------------------------------------
# create host
#    $1 : hostname
#-------------------------------------------------------------------------------
createHost_netns () {
   logMessage LOG "Creating netns $1"

   $IP netns del $1 > /dev/null 2>&1 ||$TRUE
   $IP netns add $1
   $IP netns exec $1 $IP link set lo up
}

#-------------------------------------------------------------------------------
# boot host
#    $1 : hostname
#-------------------------------------------------------------------------------
bootHost_netns () {
   logMessage LOG "Booting netns $1 (nothing done)"
}

#-------------------------------------------------------------------------------
# shutdown host
#    $1 : hostname
#-------------------------------------------------------------------------------
shutdownHost_netns () {
   logMessage LOG "Shuting down netns $1"
}

#-------------------------------------------------------------------------------
# delete host
#    $1 : hostname
#-------------------------------------------------------------------------------
deleteHost_netns () {
   logMessage LOG "Deleting netns $1"

   $IP netns del $1 > /dev/null 2>&1 ||$TRUE

   $RM -rf /etc/netns/$1
}

#-------------------------------------------------------------------------------
# return command that could open a terminal
#    $1 : hostname
#-------------------------------------------------------------------------------
yaneConsoleCmd_netns() {
   echo "$IP netns exec $1 $BASH"
}

#-------------------------------------------------------------------------------
# add an interface to an host
#    $1 : hostname
#    $2 : interface name (already created)
#    $3 : IPv4 address (or "")
#    $4 : netns in which $2 is defined
#-------------------------------------------------------------------------------
yaneAddHostInterface_netns() {
   logMessage LOG "Adding int '$2' from '$4' in netns $1"

   $IP netns exec $4 $IP link set $2 netns $1
   if [ -n "$3" ] ; then
      $IP netns exec $1 $IP link set $2 up
      $IP netns exec $1 $IP addr add $3 dev $2
   fi
}

#-------------------------------------------------------------------------------
# Have we created host $1 ?
#-------------------------------------------------------------------------------
yaneHostExists_netns() {
   if [ -z "`$IP netns list|grep $srch`" ] ; then
      return 1
   else
      return 0
   fi
}

#-------------------------------------------------------------------------------
# Populate the filesystem of an host
#    $1 : hostname
#    $2 : source basedir in the host filsystem (may be relative to .)
#    $3 : destination basedir in the guest (must be absolute)
#-------------------------------------------------------------------------------
yaneHostPopulateFS_netns() {
    logMessage LOG "Copying $2 to $3 in $1"
    $MKDIR -p /etc/netns/$1 >/dev/null 2>&1 || $TRUE
    $CP -a $2/* /etc/netns/$1 >/dev/null 2>&1 || $TRUE
}
