#!/bin/bash
#===============================================================================
# Namespace helper functions
#===============================================================================
#-------------------------------------------------------------------------------
# create host
#    $1 : hostname
#-------------------------------------------------------------------------------
createHost_namespace () {
   logMessage LOG "Creating namespace $1"

   $IP netns del $1 > /dev/null 2>&1 ||$TRUE
   $IP netns add $1
   $IP netns exec $1 $IP link set lo up
}

#-------------------------------------------------------------------------------
# kill host
#    $1 : hostname
#-------------------------------------------------------------------------------
killHost_namespace () {
   logMessage LOG "Killing namespace $1"

   $IP netns del $1 > /dev/null 2>&1 ||$TRUE

   $RM -rf /etc/netns/$1
}

#-------------------------------------------------------------------------------
# return command that could open a terminal
#    $1 : hostname
#-------------------------------------------------------------------------------
yaneConsoleCmd_namespace() {
   echo "$IP netns exec $1 $BASH"
}

#-------------------------------------------------------------------------------
# add an interface to an host
#    $1 : hostname
#    $2 : interface name (already created)
#    $3 : IPv4 address (or "")
#    $4 : namespace in which $2 is defined
#-------------------------------------------------------------------------------
yaneAddHostInterface_namespace() {
   logMessage LOG "Adding int '$2' from '$4' in namespace $1"

   $IP netns exec $4 $IP link set $2 netns $1
   if [ -n "$3" ] ; then
      $IP netns exec $1 $IP link set $2 up
      $IP netns exec $1 $IP addr add $3 dev $2
   fi
}

#-------------------------------------------------------------------------------
# Have we created host $1 ?
#-------------------------------------------------------------------------------
yaneHostExists_namespace() {
   if [ -z "`$IP netns list|grep $srch`" ] ; then
      return 1
   else
      return 0
   fi
}

#-------------------------------------------------------------------------------
# Populate the filesystem of an host
#    $1 : hostname
#    $2 : source basedir in the host filsystem (may be relative to .)
#    $3 : destination basedir in the guest (must be absolute)
#-------------------------------------------------------------------------------
yaneHostPopulateFS_namespace() {
    echo Copying $2 to $3 in $1
    $MKDIR /etc/netns/$1
    $CP -a $2/* /etc/netns/$1
}
