#-------------------------------------------------------
#   Configuration générale de yane
#-------------------------------------------------------
yane :
  verbose: True
  debug: True
  
#-------------------------------------------------------
# Paramètres par défaut d'un réseau
#-------------------------------------------------------
network :
  startup : startup.sh

#-------------------------------------------------------
# Paramètres par défaut d'un hôte
#-------------------------------------------------------
hosts :
  default :
    -
      mode: netns

#-------------------------------------------------------
# Paramètres par défaut d'un netns
#-------------------------------------------------------
netns :
  default:
    -
      files: %n/etc:/
      init: /etc/yane-guest-init %n
      
#-------------------------------------------------------
# Paramètres par défaut d'un docker
#-------------------------------------------------------
docker :
  default:
    -
      image: "alpine:latest"
      files: docker/%n:/

#-------------------------------------------------------
# Paramètres par défaut d'un docker
#-------------------------------------------------------
services :
  dnsmasq :
    -
      address: 192.168.5.1/24
      range:192.168.5.2,192.168.5.254
